##### Variables

SRCDIR = ../src ../test
#SRCDIR = src test
INCDIR = -I/usr/include -I../src -I../test
#INCDIR = -I/usr/include -Isrc -Itest
CPPFLAGS = -g -Wall -W $(INCDIR) 
LFLAGS = -lm -lpthread -lwiringPi
CC = gcc

##### Files

SOURCES = $(wildcard *.c)
OBJECTS = $(patsubst %.c,%.o,$(wildcard *.c))
TARGET = sdieh

##### Build rules

all: $(OBJECTS)
	$(CC) $(CPPFLAGS) $(OBJECTS) $(LFLAGS) -o $(TARGET)

import:
	@rm -f *.c *~
	@for dir in $(SRCDIR); do find $$dir -name \*.c -exec ln -s {} \; ; done

depend:
	@makedepend $(INCDIR) -Y -m $(SOURCES) 2> /dev/null

clean:
	@rm -f *.o *.bak *~ *%

##### End of Makefile
# DO NOT DELETE

aaa.o: ../src/aaa.h /usr/include/stdio.h /usr/include/features.h
aaa.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
main.o: /usr/include/stdio.h /usr/include/features.h /usr/include/libio.h
main.o: /usr/include/_G_config.h /usr/include/wchar.h ../src/params.h
main.o: ../src/sdisys.h ../src/aaa.h
params.o: ../src/params.h
sdisys.o: ../src/sdisys.h /usr/include/stdio.h /usr/include/features.h
sdisys.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
